apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iota-agent.fullname" . }}--config
data:
  DEPTH: {{ .Values.iota.depth | quote }}
  MINIMUM_WEIGHT_MAGNITUDE : {{ .Values.iota.mwm | quote }}
  PROVIDER: {{ .Values.iota.provider | quote }}
  SECURITY_LEVEL: {{ .Values.iota.securityLevel | quote }}
  MAM_MODE: {{ .Values.iota.mam.mode | quote }}
  LOG_LEVEL: {{ .Values.logging.level | quote }}
  PORT: "3000"
  ENABLED: {{ .Values.jsonDB.enabled | quote }}
  JSON_DB_PATH: {{ .Values.jsonDB.path | quote }}
  JAEGER_ENABLED: {{.Values.jaeger.enabled | quote }}
  JAEGER_HOST: {{.Values.jaeger.host | quote }}
  JAEGER_SAMPLER_PARAM: {{.Values.jaeger.sampler.param | quote }}
  JAEGER_SAMPLER_TYPE: {{.Values.jaeger.sampler.type | quote }}
  JAEGER_SERVICE_NAME: {{.Values.jaeger.serviceName | quote }}
  JAEGER_AGENT_SIDECAR_ENABLED: {{.Values.jaeger.agent.sidecar.enabled | quote }}