apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "PGP-Service.fullname" . }}--pgp--config
data:
  PGP_SECRET: {{ .Values.pgp.config.secret | quote }}
  PGP_KEY_PATH  : {{ .Values.pgp.config.keyPath | quote }}
  PGP_KEY_TYPE  : {{ .Values.pgp.config.keyType | quote }}
  HKP_ADDRESS  : {{ .Values.pgp.config.hkpAddress | quote }}
  PGP_KEY_ID_EMAIL : {{ .Values.pgp.config.id.email | quote }}
  PGP_KEY_ID_NAME : {{ .Values.pgp.config.id.name | quote }}
  PGP_SERVICE_ADDRESS: {{ .Values.pgp.serviceAddress | quote }}
  PGP_LOG_LEVEL: {{ .Values.pgp.logLevel | quote }}