apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.databaseAgent.depname }}-config
data:
  LOG_LEVEL: {{ .Values.logging.level | quote }}
  PORT: {{ .Values.databaseAgent.port | quote }}
  MONGO_HOST: {{ .Values.databaseAgent.mongohost | quote }}
  MONGO_PASS_KEY: {{ .Values.databaseAgent.mongoPasswordKey | quote }}
  MONGO_PORT: "27017"
  MONGO_USER: root
  MONGO_REPLICA_SET_NAME: {{ .Values.databaseAgent.mongoReplicaSetName | quote }}
  CHANNEL_DB: primary
  AUDIT_POSTFIX: _audit
  JAEGER_ENABLED: {{.Values.jaeger.enabled | quote }}
  JAEGER_HOST: {{.Values.jaeger.host | quote }}
  JAEGER_SAMPLER_PARAM: {{.Values.jaeger.sampler.param | quote }}
  JAEGER_SAMPLER_TYPE: {{.Values.jaeger.sampler.type | quote }}
  JAEGER_SERVICE_NAME: {{.Values.jaeger.serviceName | quote }}
  JAEGER_AGENT_SIDECAR_ENABLED: {{.Values.jaeger.agent.sidecar.enabled | quote }}
  MONGO_SERVER_SELECTION_TIMEOUT: {{ .Values.databaseAgent.mongoServerSelectionTimeout }}
  MONGO_CONNECTION_TIMEOUT: {{ .Values.databaseAgent.mongoConnectionTimeout }}
  {{ if .Values.databaseAgent.mongoTLS.enabled }}
  MONGO_TLS_MODE_ENABLED: "1"
  MONGO_TLS_CA_CERT_PATH: {{ .Values.databaseAgent.mongoTLS.certs.secretPath }}{{ .Values.databaseAgent.mongoTLS.certs.caCertKey }}
  MONGO_TLS_CLIENT_CERT_PATH: {{ .Values.databaseAgent.mongoTLS.certs.secretPath }}{{ .Values.databaseAgent.mongoTLS.certs.clientCertKey }}
  {{ if .Values.databaseAgent.mongoTLS.allowInvalidHosts }}
  MONGO_TLS_ALLOW_INVALID_HOST: "1" 
  {{ end }}
  {{ if .Values.databaseAgent.mongoTLS.certs.clientCertIsEncrypted }}
  MONGO_TLS_CLIENT_CERT_PASS_KEY: {{ .Values.databaseAgent.mongoTLS.certs.clientCertPassKey | quote}}
  {{ end }}
  {{ end }}
