apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "database-agent.fullname" . }}
  labels:
  {{- include "database-agent.labels" . | nindent 4 }}
  annotations:
    {{- if  .Values.jaeger.agent.sidecar.enabled }}
    sidecar.jaegertracing.io/inject: {{ .Values.jaeger.agent.sidecar.name | quote  }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "database-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "database-agent.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "database-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3500
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{.Values.databaseAgent.depname}}-config
            - secretRef:
                name: {{.Values.databaseAgent.mongoSecret}}
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
