apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chainsource-gateway.fullname" . }}--pgp--config
data:
  HKP_ADDRESS  : {{ .Values.pgp.config.hkpAddress | quote }}
  PGP_SERVICE_ADDRESS: {{ .Values.pgp.serviceAddress | quote }}