version: "3"
services:
  mongo_db_service:
    container_name: mongo_db_service
    restart: always
    build: 
      context: ./config/mongodb_replica
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: dbom
      MONGO_REPLICA_HOST: mongo_db_service
      MONGO_REPLICA_PORT: 27018
    ports:
      - 27018:27018
    volumes:
      - mongo_db_service:/data/db
    networks:
      - dbom-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27018/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  nats_service:
      image: nats:latest
      command: -c /nat_server.conf --name natsservice -p 4222
      volumes:
        - ./config/nats/server.conf:/nat_server.conf
      ports:
        - 4222:4222
      networks:
        - dbom-network
      healthcheck:
        test: ["CMD", "nats", "-z", "nats://localhost:4222"]
        interval: 5s  
        timeout: 10s 
        retries: 3

  database_agent_service:
    container_name: database_agent_service
    image: dbomproject/database-agent:2.0.0-alpha-1
    depends_on:
      - nats_service
      - mongo_db_service
    links:
      - nats_service
      - mongo_db_service
    command: ["sh", "-c", "sleep 5 && npm run migrate && npm run start"]
    environment:
      NATS_URI: nats://nats_service:4222
      DATABASE_URL: mongodb://root:prisma@mongo_db_service:27018/dbom?authSource=admin
      NODE_ID: node1
    networks:
      - dbom-network

  chainsource_gateway_service:
    container_name: node1.test.com
    image: dbomproject/chainsource-gateway:2.0.0-alpha-1
    ports:
      - 3050:3050
      - 7205:7205
    depends_on:
      - nats_service
    links:
      - nats_service
    environment:
      NATS_URI: nats://nats_service:4222
      PORT: 3050
      FED_PORT: 7205
      LOG_LEVEL: info
      NODE_ID: node1
      NODE_URI: node1.test.com
      NODE_CERT_PATH: /app/certs/node1.test.com.crt
      NODE_KEY_PATH: /app/certs/node1.test.com.key
      CA_CERT_PATH: /app/certs/ca.crt
    volumes:
      - ./certs/node1.test.com.crt:/app/certs/node1.test.com.crt
      - ./certs/node1.test.com.key:/app/certs/node1.test.com.key
      - ./certs/ca.crt:/app/certs/ca.crt
    networks:
      - dbom-network

volumes:
  mongo_db_service: {}

networks:
  dbom-network:
    driver: bridge