version: "3.8"
services:
  iota-agent:
    build: ../iota-agent
    networks:
      - dbom
    expose:
      - "4000"
    environment:
      - DEPTH=3
      - MINIMUM_WEIGHT_MAGNITUDE=3
      - PROVIDER=https://nodes.comnet.thetangle.org:443
      - SECURITY_LEVEL=2
      - MAM_MODE=restricted
      - LOG_LEVEL=info
      - PORT=4000
      - ENABLED=true
    volumes:
      - iota_data:/usr/src/app/db

volumes:
  iota_data:

networks:
  dbom: