version: "3"
services:
  nats_service:
    image: nats:latest
    command: -c /nat_server.conf --name natsservice -p 4222
    volumes:
      - ./server.conf:/nat_server.conf
    ports:
      - 4222:4222
    networks:
      - dbom-network
  mongo_db_service:
    container_name: mongo_db_service
    restart: always
    build: 
      context: ../../database-agent/src/mongodb_replica
      dockerfile: ./Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: dbom
      MONGO_REPLICA_HOST: mongo_db_service
      MONGO_REPLICA_PORT: 27018
    logging:
      driver: none # Disable logging for this container
    ports:
      - 27018:27018
    volumes:
      - mongo_db_service:/data/db
    networks:
      - dbom-network

  database_agent_service:
    container_name: database_agent_service
    restart: always
    build:
      context: ../../database-agent
      dockerfile: ./Dockerfile
    depends_on:
      - nats_service
      - mongo_db_service
    links:
      - nats_service
      - mongo_db_service
    command: ["sh", "-c", "sleep 2 && npm run migrate && npm run start"]
    environment:
      NATS_URI: nats://nats_service:4222
      DATABASE_URL: mongodb://root:prisma@mongo_db_service:27018/dbom?authSource=admin
      NODE_ID: node1
    networks:
      - dbom-network

  chainsource_gateway_service:
    container_name: node1.test.com
    build:
      context: ../../chainsource-gateway
      dockerfile: ./Dockerfile
    ports:
      - 3050:3050
      - 7205:7205
    depends_on:
      - nats_service
    links:
      - nats_service
    environment:
      NATS_URI: nats://nats_service:4222
      PORT: 3050
      FED_PORT: 7205
      LOG_LEVEL: info
      NODE_ID: node1
      NODE_URI: node1.test.com

    networks:
      - dbom-network

volumes:
  mongo_db_service: {}

networks:
  dbom-network:
    driver: bridge